### ISSUE TITLE
Expanding window (aka "stretch") from specific date, not just the beginning of the data frame

### ISSUE THREAD

**Issue by adhi-r** [DavisVaughan/slider#87] opened 2020-04-16 22:31 UTC
Hi,

Firstly thanks for your great work on a very powerful package.

In the docs there is an example where the user can set `.before = Inf` to get a window that continues to expand from that value. Is there a way to set some arbritrary index value (I'm using date in this case) as the "anchor" for the function to go back to always?

My goal is to take a daily series of data, and index the values to Feb 1 within `mutate()`. So in the new column Feb 1 = 100, and if the value on Mar 5 is 27% higher than on Feb 1, the new value for Mar 5 = 127. But I don't want to be throwing out all data before Feb 1, because I'm doing this across multiple years.

A hacky solution would be to make a dataframe with the Feb 1 data and then left join it in, but I was wondering if slider could handle this natively.

**Comment by DavisVaughan** [comment] 2020-04-16 23:44
Could you please provide a reproducible example of what you are trying to do? Even if it’s done in the hacky way, it will be easier for me to try and understand. (If you can make it as close to your real example, that would be helpful too!)

**Comment by DavisVaughan** [comment] 2020-04-23 01:09
Closing unless a more specific example can be added!

**Closed** 2020-04-23 01:09 UTC

**Comment by sstoeckl** [comment] 2020-04-27 22:07
I think I understand: I am doing regressions on recursively expanding windows using `slider` and `.before=Inf`. This starts with a regression with just one row in the data.frame. What I would be looking for would be something along the lines of: Do a recursive window regression, but do start 12 month after the initial date to save time and space. So if data starts at 2018-01-01 you would like the first expanding window regression to start in 2019-01-01 (with 12 months into the regression).

**Comment by DavisVaughan** [comment] 2020-04-28 13:23
It sounds like you want `hop_index()`. This is a more granular version of `slide_index()` that allows you to control the start/stop values of where to search for the `.i`ndex value.

So you'd supply the first `stops` value to be 2019-01-01, with a lookback period of however long you want (here i choose `years(1)`). And then the rest of the `stops` values are past the first one.

The size of the object returned is always equal to the size of the `.starts` and the `.stops`. This is different from `slide_index()` which returns something with size equal to `.x`. But its nice here because you can make a data frame of the results, lining it up with your starts and stops.

``` r
library(slider)
library(lubridate)
library(tibble)

index <- as.Date("2018-01-01") + months(0:24)

first <- index[[1]] + years(1)
first
#> [1] "2019-01-01"

before <- years(1)

stops <- index[index >= first]
starts <- stops - before

results <- hop_index(
  .x = index, 
  .i = index, 
  .starts = starts, 
  .stops = stops,
  .f = ~.x
)

head(results)
#> [[1]]
#>  [1] "2018-01-01" "2018-02-01" "2018-03-01" "2018-04-01" "2018-05-01"
#>  [6] "2018-06-01" "2018-07-01" "2018-08-01" "2018-09-01" "2018-10-01"
#> [11] "2018-11-01" "2018-12-01" "2019-01-01"
#> 
#> [[2]]
#>  [1] "2018-02-01" "2018-03-01" "2018-04-01" "2018-05-01" "2018-06-01"
#>  [6] "2018-07-01" "2018-08-01" "2018-09-01" "2018-10-01" "2018-11-01"
#> [11] "2018-12-01" "2019-01-01" "2019-02-01"
#> 
#> [[3]]
#>  [1] "2018-03-01" "2018-04-01" "2018-05-01" "2018-06-01" "2018-07-01"
#>  [6] "2018-08-01" "2018-09-01" "2018-10-01" "2018-11-01" "2018-12-01"
#> [11] "2019-01-01" "2019-02-01" "2019-03-01"
#> 
#> [[4]]
#>  [1] "2018-04-01" "2018-05-01" "2018-06-01" "2018-07-01" "2018-08-01"
#>  [6] "2018-09-01" "2018-10-01" "2018-11-01" "2018-12-01" "2019-01-01"
#> [11] "2019-02-01" "2019-03-01" "2019-04-01"
#> 
#> [[5]]
#>  [1] "2018-05-01" "2018-06-01" "2018-07-01" "2018-08-01" "2018-09-01"
#>  [6] "2018-10-01" "2018-11-01" "2018-12-01" "2019-01-01" "2019-02-01"
#> [11] "2019-03-01" "2019-04-01" "2019-05-01"
#> 
#> [[6]]
#>  [1] "2018-06-01" "2018-07-01" "2018-08-01" "2018-09-01" "2018-10-01"
#>  [6] "2018-11-01" "2018-12-01" "2019-01-01" "2019-02-01" "2019-03-01"
#> [11] "2019-04-01" "2019-05-01" "2019-06-01"

tibble(
  start = starts,
  stop = stops,
  result = results
)
#> # A tibble: 13 x 3
#>    start      stop       result     
#>    <date>     <date>     <list>     
#>  1 2018-01-01 2019-01-01 <date [13]>
#>  2 2018-02-01 2019-02-01 <date [13]>
#>  3 2018-03-01 2019-03-01 <date [13]>
#>  4 2018-04-01 2019-04-01 <date [13]>
#>  5 2018-05-01 2019-05-01 <date [13]>
#>  6 2018-06-01 2019-06-01 <date [13]>
#>  7 2018-07-01 2019-07-01 <date [13]>
#>  8 2018-08-01 2019-08-01 <date [13]>
#>  9 2018-09-01 2019-09-01 <date [13]>
#> 10 2018-10-01 2019-10-01 <date [13]>
#> 11 2018-11-01 2019-11-01 <date [13]>
#> 12 2018-12-01 2019-12-01 <date [13]>
#> 13 2019-01-01 2020-01-01 <date [13]>
```

<sup>Created on 2020-04-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DavisVaughan** [comment] 2020-04-28 13:25
To use an expanding window, you can use a single `.starts` value pinned to the first value in your index. 

``` r
library(slider)
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following objects are masked from 'package:base':
#> 
#>     date, intersect, setdiff, union
library(tibble)
#> Warning: package 'tibble' was built under R version 3.6.2

index <- as.Date("2018-01-01") + months(0:24)

first <- index[[1]] + years(1)
first
#> [1] "2019-01-01"

stops <- index[index >= first]
starts <- index[[1]]

results <- hop_index(
  .x = index, 
  .i = index, 
  .starts = starts, 
  .stops = stops,
  .f = ~.x
)

head(results)
#> [[1]]
#>  [1] "2018-01-01" "2018-02-01" "2018-03-01" "2018-04-01" "2018-05-01"
#>  [6] "2018-06-01" "2018-07-01" "2018-08-01" "2018-09-01" "2018-10-01"
#> [11] "2018-11-01" "2018-12-01" "2019-01-01"
#> 
#> [[2]]
#>  [1] "2018-01-01" "2018-02-01" "2018-03-01" "2018-04-01" "2018-05-01"
#>  [6] "2018-06-01" "2018-07-01" "2018-08-01" "2018-09-01" "2018-10-01"
#> [11] "2018-11-01" "2018-12-01" "2019-01-01" "2019-02-01"
#> 
#> [[3]]
#>  [1] "2018-01-01" "2018-02-01" "2018-03-01" "2018-04-01" "2018-05-01"
#>  [6] "2018-06-01" "2018-07-01" "2018-08-01" "2018-09-01" "2018-10-01"
#> [11] "2018-11-01" "2018-12-01" "2019-01-01" "2019-02-01" "2019-03-01"
#> 
#> [[4]]
#>  [1] "2018-01-01" "2018-02-01" "2018-03-01" "2018-04-01" "2018-05-01"
#>  [6] "2018-06-01" "2018-07-01" "2018-08-01" "2018-09-01" "2018-10-01"
#> [11] "2018-11-01" "2018-12-01" "2019-01-01" "2019-02-01" "2019-03-01"
#> [16] "2019-04-01"
#> 
#> [[5]]
#>  [1] "2018-01-01" "2018-02-01" "2018-03-01" "2018-04-01" "2018-05-01"
#>  [6] "2018-06-01" "2018-07-01" "2018-08-01" "2018-09-01" "2018-10-01"
#> [11] "2018-11-01" "2018-12-01" "2019-01-01" "2019-02-01" "2019-03-01"
#> [16] "2019-04-01" "2019-05-01"
#> 
#> [[6]]
#>  [1] "2018-01-01" "2018-02-01" "2018-03-01" "2018-04-01" "2018-05-01"
#>  [6] "2018-06-01" "2018-07-01" "2018-08-01" "2018-09-01" "2018-10-01"
#> [11] "2018-11-01" "2018-12-01" "2019-01-01" "2019-02-01" "2019-03-01"
#> [16] "2019-04-01" "2019-05-01" "2019-06-01"

tibble(
  start = starts,
  stop = stops,
  result = results
)
#> # A tibble: 13 x 3
#>    start      stop       result     
#>    <date>     <date>     <list>     
#>  1 2018-01-01 2019-01-01 <date [13]>
#>  2 2018-01-01 2019-02-01 <date [14]>
#>  3 2018-01-01 2019-03-01 <date [15]>
#>  4 2018-01-01 2019-04-01 <date [16]>
#>  5 2018-01-01 2019-05-01 <date [17]>
#>  6 2018-01-01 2019-06-01 <date [18]>
#>  7 2018-01-01 2019-07-01 <date [19]>
#>  8 2018-01-01 2019-08-01 <date [20]>
#>  9 2018-01-01 2019-09-01 <date [21]>
#> 10 2018-01-01 2019-10-01 <date [22]>
#> 11 2018-01-01 2019-11-01 <date [23]>
#> 12 2018-01-01 2019-12-01 <date [24]>
#> 13 2018-01-01 2020-01-01 <date [25]>
```

<sup>Created on 2020-04-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
